/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package common;

import java.io.File;

public class Library {
    public static void outputCurrentDirectory() {
        System.out.println("current dir: " + new File(".").getAbsoluteFile().getParent());
    }
}
