/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;

import org.apache.http.HttpEntity;
import org.apache.http.HttpResponse;
import org.apache.http.HttpStatus;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClientBuilder;

/**
 * HTTPClient
 *
 */
public class HTTPClient {
    /**
     * HTTPプロトコルを使用してファイルをダウンロードする.
     *
     * @param url
     * @param destFilepath
     * @return
     * @throws HTTPClientException
     */
    public void download(final String url, final String destFilepath) throws HTTPClientException {
        CloseableHttpClient client = HttpClientBuilder.create().build();
        HttpGet request = new HttpGet(url);

        HttpResponse response;
        try {
            response = client.execute(request);
        } catch (IOException e) {
            try {
                client.close();
            } catch (IOException e1) {
                e1.printStackTrace();
            }
            throw new HTTPClientException("HTTP GETリクエストの発行中にエラーが発生ました。", e);
        }

        HttpEntity entity = response.getEntity();
        int statusCode = response.getStatusLine().getStatusCode();
        if (HttpStatus.SC_OK != statusCode) {
            try {
                client.close();
            } catch (IOException e1) {
                e1.printStackTrace();
            }
            throw new HTTPClientException("HTTP GETリクエストのステータスコードが" + statusCode + " です。");
        }

        InputStream is = null;
        try {
            is = entity.getContent();

        } catch (UnsupportedOperationException | IOException e) {
            try {
                client.close();
            } catch (IOException e1) {
                e1.printStackTrace();
            }
            throw new HTTPClientException("GETした内容の読込に失敗しました。", e);
        }

        FileOutputStream fos = null;
        try {
            fos = new FileOutputStream(new File(destFilepath));
        } catch (FileNotFoundException e) {
            try {
                is.close();
                client.close();
            } catch (IOException e1) {
                e1.printStackTrace();
            }
            throw new HTTPClientException("出力先が存在しません。", e);
        }

        int inByte;
        try {
            while ((inByte = is.read()) != -1) {
                fos.write(inByte);
            }
        } catch (IOException e) {
            try {
                fos.close();
                is.close();
                client.close();
            } catch (IOException e1) {
                e1.printStackTrace();
            }
            throw new HTTPClientException("GETした内容の出力先への書込みに失敗しました。", e);
        }

        try {
            fos.close();
            is.close();
            client.close();
        } catch (IOException e1) {
            e1.printStackTrace();
        }
    }
}
