/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package multipj.common;

import java.io.File;

import org.apache.commons.lang3.StringUtils;

public class Common {
    /**
     * 実験用に Apache Commons Lang を使用する
     */
    public void useCommonsLang3() {
        String currentDir = Common.getCurrentDirPath();
        if (StringUtils.startsWith(currentDir, "C")) {
            System.out.println(Common.getClassName() + "#" + Common.getMethodName() + ": This Program is running in C drive.");
        }
    }

    /**
     * 実行中のクラス名を取得する.
     * @return クラス名
     */
    public static String getClassName() {
        return Thread.currentThread().getStackTrace()[2].getClassName();
    }

    /**
     * 実行中のメソッド名を取得する.
     * @return メソッド名
     */
    public static String getMethodName() {
        return Thread.currentThread().getStackTrace()[2].getMethodName();
    }

    /**
     * カレントディレクトリを取得する.
     * @return カレントディレクトリのパス
     */
    public static String getCurrentDirPath() {
        return new File(".").getAbsoluteFile().getParent();
    }
}
